### ISSUE TITLE
Parsing with some error

### ISSUE THREAD

**Issue by hyichao** [vadimkantorov/caffemodel2json#1]
Hello,

I use your tool to parse a `.caffemodel` file and it did work. But when I open the `.json` file I found the following: 

``` json
{
          "shape": {
            "dim": [
              32, 
              16, 
              3, 
              3
            ]
          }, 
          "data": [
            0.00726931169629097, 
            0.005067944992333651, 
            -0.0055292085744440556, 
            0.010629781521856785, 
            -0.0010661107953637838, 
            "(4603 elements more)"
          ]
        }, 
```

The data part is somehow not fully recorded. And I don't know if this is a bug of the tool or it is due to limitation of json. Could you please tell me how to fix this? I need all the weights from `.caffemodel`.

Thanks a lot.

**Comment by hyichao** [comment]
oops..

I found some codes causes this error.

``` python
if not print_arrays and (field.name == 'data' and len(js_value) > 8):
    head_n = 5
    js_value = js_value[:head_n] + ['(%d elements more)' % (len(js_value) - head_n)]
```

I will fix this myself. Thanks for the tool again.

**Comment by vadimkantorov** [comment]
Yes, you need to add the switch `--data` to print everything.
